<a href="https://colab.research.google.com/github/harifaly/Python_for_data_science/blob/main/__pandas__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print("___pandas____")

___pandas____

In [5]:
# faut importer le package pandas
import pandas as pd

In [6]:
import numpy as np

In [7]:
# A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

# --- Création ---
df = pd.DataFrame({
    'nom':    ['Alice', 'Bob', 'Clara', 'David'],
    'age':    [25, 30, np.nan, 22],
    'score':  [88, 75, 92, 60],
    'ville':  ['Paris', 'Lyon', 'Paris', 'Lyon']
})

In [8]:
print(df)

     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon

if you want to import a csv or excel file

you can use:

df = read_csv('data.csv')

or

df = read_excel('data.xlsx')

In [9]:
#____Exploration__
print("afficher les debuts de dataframe\n__________________________")
print(df.head())
print("___________________\nafficher les fins de dataframe\n________________________")
print(df.tail())
print("__________________\nafficher les informations de dataframe\n____________________")
print(df.info())
print("___________________\nstatistique rapide\n_____________________")
print(df.describe())

afficher les debuts de dataframe
__________________________
     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon
___________________
afficher les fins de dataframe
________________________
     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon
__________________
afficher les informations de dataframe
____________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nom     4 non-null      object
 1   age     3 non-null      float64
 2   score   4 non-null      int64
 3   ville   4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes
None
___________________
statistique rapide
_____________________
             age     score
count   3.000000   4.00000
mean   25.666667  78.75000
std     4.041452  14.45395
min    22.000000  60.00000
25%    23.500000  71.25000
50%    25.000000  81.50000
75%    27.500000  89.00000
max    30.000000  92.00000

In [10]:
# --- Sélection --------
print(df['score'])              #afficher une colonne

0    88
1    75
2    92
3    60
Name: score, dtype: int64

In [11]:
print(df[['nom', 'score']])     #afficher  plusieurs colonnes

     nom  score
0  Alice     88
1    Bob     75
2  Clara     92
3  David     60

In [12]:
print(df[df['score'] > 70])     # filtre conditionnel

     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris

In [13]:
# loc sert à sélectionner des données par leurs labels (index et noms de colonnes).
# suntax:  df.loc[ligne, colonne]===> ca sert à sélectionner des données par leurs labels

print(df.loc[0, 'nom'])         # par label

Alice

In [14]:
print(df.iloc[0, 1])

# Il sert à accéder aux données par position (numéro)

25.0

In [15]:
# ______Valeurs manquantes_________
print(df.isnull().sum())         # compter les NaN

nom      0
age      1
score    0
ville    0
dtype: int64

In [16]:
print(df['age'].dtype)

float64

In [17]:
df

     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon

In [18]:
df['age']=df['age'].fillna(df['age'].mean())  # remplacer par moyenne

In [19]:
df

     nom        age  score  ville
0  Alice  25.000000     88  Paris
1    Bob  30.000000     75   Lyon
2  Clara  25.666667     92  Paris
3  David  22.000000     60   Lyon

In [20]:
df.dropna(inplace=True)    # ou supprimer les lignes

In [21]:
df

     nom        age  score  ville
0  Alice  25.000000     88  Paris
1    Bob  30.000000     75   Lyon
2  Clara  25.666667     92  Paris
3  David  22.000000     60   Lyon

# ***GROUPBY***

sert à regrouper les données selon une colonne, puis appliquer une opération

In [22]:
#____GroupBy______
print(df.groupby('ville')['score'].mean())   # moyenne par ville

ville
Lyon     67.5
Paris    90.0
Name: score, dtype: float64

In [23]:
print(df.groupby('ville').agg({'score': ['mean', 'max', 'count']}))

      score
       mean max count
ville
Lyon   67.5  75     2
Paris  90.0  92     2

autre operation

In [24]:
# somme
df.groupby('ville')['score'].sum()

ville
Lyon     135
Paris    180
Name: score, dtype: int64

In [25]:
# compter
df.groupby('ville')['nom'].count()

ville
Lyon     2
Paris    2
Name: nom, dtype: int64

In [26]:
# max
df.groupby('ville')['score'].max()

ville
Lyon     75
Paris    92
Name: score, dtype: int64

In [28]:
# exemple plusieur colonnes
df.groupby('ville')[['age', 'score']].mean()

             age  score
ville
Lyon   26.000000   67.5
Paris  25.333333   90.0