<a href="https://colab.research.google.com/github/harifaly/Python_for_data_science/blob/main/__pandas__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
print("___pandas____")

___pandas____

In [90]:
# faut importer le package pandas
import pandas as pd

In [91]:
import numpy as np

In [92]:
# A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

# --- Création ---
df = pd.DataFrame({
    'nom':    ['Alice', 'Bob', 'Clara', 'David'],
    'age':    [25, 30, np.nan, 22],
    'score':  [88, 75, 92, 60],
    'ville':  ['Paris', 'Lyon', 'Paris', 'Lyon']
})

In [93]:
print(df)

     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon

if you want to import a csv or excel file

you can use:

df = read_csv('data.csv')

or

df = read_excel('data.xlsx')

In [94]:
#____Exploration__
print("afficher les debuts de dataframe\n__________________________")
print(df.head())
print("___________________\nafficher les fins de dataframe\n________________________")
print(df.tail())
print("__________________\nafficher les informations de dataframe\n____________________")
print(df.info())
print("___________________\nstatistique rapide\n_____________________")
print(df.describe())

afficher les debuts de dataframe
__________________________
     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon
___________________
afficher les fins de dataframe
________________________
     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon
__________________
afficher les informations de dataframe
____________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nom     4 non-null      object
 1   age     3 non-null      float64
 2   score   4 non-null      int64
 3   ville   4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes
None
___________________
statistique rapide
_____________________
             age     score
count   3.000000   4.00000
mean   25.666667  78.75000
std     4.041452  14.45395
min    22.000000  60.00000
25%    23.500000  71.25000
50%    25.000000  81.50000
75%    27.500000  89.00000
max    30.000000  92.00000

In [95]:
# --- Sélection --------
print(df['score'])              #afficher une colonne

0    88
1    75
2    92
3    60
Name: score, dtype: int64

In [96]:
print(df[['nom', 'score']])     #afficher  plusieurs colonnes

     nom  score
0  Alice     88
1    Bob     75
2  Clara     92
3  David     60

In [97]:
print(df[df['score'] > 70])     # filtre conditionnel

     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris

In [98]:
# loc sert à sélectionner des données par leurs labels (index et noms de colonnes).
# suntax:  df.loc[ligne, colonne]===> ca sert à sélectionner des données par leurs labels

print(df.loc[0, 'nom'])         # par label

Alice

In [99]:
print(df.iloc[0, 1])

# Il sert à accéder aux données par position (numéro)

25.0

In [100]:
# ______Valeurs manquantes_________
print(df.isnull().sum())         # compter les NaN

nom      0
age      1
score    0
ville    0
dtype: int64

In [101]:
print(df['age'].dtype)

float64

In [102]:
df

     nom   age  score  ville
0  Alice  25.0     88  Paris
1    Bob  30.0     75   Lyon
2  Clara   NaN     92  Paris
3  David  22.0     60   Lyon

In [103]:
df['age']=df['age'].fillna(df['age'].mean())  # remplacer par moyenne

In [104]:
df

     nom        age  score  ville
0  Alice  25.000000     88  Paris
1    Bob  30.000000     75   Lyon
2  Clara  25.666667     92  Paris
3  David  22.000000     60   Lyon

In [105]:
df.dropna(inplace=True)    # ou supprimer les lignes

In [106]:
df

     nom        age  score  ville
0  Alice  25.000000     88  Paris
1    Bob  30.000000     75   Lyon
2  Clara  25.666667     92  Paris
3  David  22.000000     60   Lyon

# ***GROUPBY***

sert à regrouper les données selon une colonne, puis appliquer une opération

In [107]:
#____GroupBy______
print(df.groupby('ville')['score'].mean())   # moyenne par ville

ville
Lyon     67.5
Paris    90.0
Name: score, dtype: float64

In [108]:
print(df.groupby('ville').agg({'score': ['mean', 'max', 'count']}))

      score
       mean max count
ville
Lyon   67.5  75     2
Paris  90.0  92     2

autre operation

In [109]:
# somme
df.groupby('ville')['score'].sum()

ville
Lyon     135
Paris    180
Name: score, dtype: int64

In [110]:
# compter
df.groupby('ville')['nom'].count()

ville
Lyon     2
Paris    2
Name: nom, dtype: int64

In [111]:
# max
df.groupby('ville')['score'].max()

ville
Lyon     75
Paris    92
Name: score, dtype: int64

In [112]:
# exemple plusieur colonnes
df.groupby('ville')[['age', 'score']].mean()

             age  score
ville
Lyon   26.000000   67.5
Paris  25.333333   90.0

# SERIES

Une Series = une colonne de données (1 dimension)

C’est comme une liste améliorée avec des index

In [113]:
# exemple
s = pd.Series([10, 20, 30])
print(s)
print("Une Series a 2 choses:\nindex → 0, 1, 2\nvaleurs → 10, 20, 30")

0    10
1    20
2    30
dtype: int64
Une Series a 2 choses:
index → 0, 1, 2
valeurs → 10, 20, 30

In [114]:
# On peut personnaliser les indexs
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

In [115]:
print(s)

a    10
b    20
c    30
dtype: int64

Series = colonne unique + index

DataFrame = plusieurs Series

MERGE|

In [116]:
# _______MERGE_________
# merge sert à combiner deux DataFrames selon une clé commune

In [117]:
# exemple pour nos data
df2 = pd.DataFrame({'nom': ['Alice', 'Bob'], 'niveau': ['junior', 'senior']})
merged = pd.merge(df, df2, on='nom', how='left')
print(merged)

     nom        age  score  ville  niveau
0  Alice  25.000000     88  Paris  junior
1    Bob  30.000000     75   Lyon  senior
2  Clara  25.666667     92  Paris     NaN
3  David  22.000000     60   Lyon     NaN

In [118]:
# exemple basique
toM1 = pd.DataFrame({
    'id': [1, 2, 3],
    'nom': ['Alice', 'Bob', 'Clara']
})

In [119]:
toM2= pd.DataFrame({
    'id': [1, 2, 4],
    'score': [90, 80, 70]
})

In [120]:
print(toM1)
print("\n",toM2)

   id    nom
0   1  Alice
1   2    Bob
2   3  Clara

    id  score
0   1     90
1   2     80
2   4     70

In [121]:
df_merged = pd.merge(toM1, toM2, on='id')
print(df_merged)

   id    nom  score
0   1  Alice     90
1   2    Bob     80

In [122]:
# Type de merge
# INNER(default)  il garde que l'intersection
inner = pd.merge(toM1, toM2, on='id', how='inner')
print(inner)

   id    nom  score
0   1  Alice     90
1   2    Bob     80

In [123]:
# LEFT garde tout toM1
left = pd.merge(toM1, toM2, on='id', how='left')
print(left)
print("ici ,Clara n'a pas de score car elle n'a pas de id dans toM1")

   id    nom  score
0   1  Alice   90.0
1   2    Bob   80.0
2   3  Clara    NaN
ici ,Clara n'a pas de score car elle n'a pas de id dans toM1

In [124]:
# RIGHT
right = pd.merge(toM1, toM2, on='id', how='right')
print(right)

   id    nom  score
0   1  Alice     90
1   2    Bob     80
2   4    NaN     70

In [125]:
# OUTER
outer = pd.merge(toM1, toM2, on='id', how='outer')
print(outer)
print("outer : garde tout")

   id    nom  score
0   1  Alice   90.0
1   2    Bob   80.0
2   3  Clara    NaN
3   4    NaN   70.0
outer : garde tout

APPLY FUNCTION

apply sert à appliquer une fonction sur: series et dataframe

In [126]:
print(df)
# note : age de clara est a l'origine Nan et on a remplace ca par la moyenne

     nom        age  score  ville
0  Alice  25.000000     88  Paris
1    Bob  30.000000     75   Lyon
2  Clara  25.666667     92  Paris
3  David  22.000000     60   Lyon

In [127]:
# exemple : ajouter 1 a chaque age de notre premiere dataframe (cols : age)
df['age'].apply(lambda x: x + 1)

0    26.000000
1    31.000000
2    26.666667
3    23.000000
Name: age, dtype: float64

In [88]:
# exemple : STANDARISATION (Z-score)
df['score_norm'] = df['score'].apply(lambda x: (x - df['score'].mean()) / df['score'].std())

In [128]:
print(df)

     nom        age  score  ville
0  Alice  25.000000     88  Paris
1    Bob  30.000000     75   Lyon
2  Clara  25.666667     92  Paris
3  David  22.000000     60   Lyon